#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/*.yaml

## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
## ！！！只有这份文件的端口设置会随ClashX启动生效

## 如果您不知道如何操作，请参阅 官方Github文档 https://github.com/Dreamacro/clash/blob/dev/README.md
#---------------------------------------------------#

# (HTTP and SOCKS5 in one port)
mixed-port: 1087
# RESTful API for clash
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: warning

proxies:

proxy-groups:
  - name: PROXY
    type: url-test
    url: https://www.google.com
    interval: 300
    use:
      - github
      - github1
      - github2
      - github3
      - github4

  - name: 手动节点
    type: select
    use:
      - github
      - github1
      - github2
      - github3
      - github4

proxy-providers:
  github: # provider的名称，后期会用到
    type: http
    path: ./profiles/github.yml # 保存在本地文件的名字，可以随便取
    url: https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml
    interval: 36000 # 每36000秒更新一次订阅
    health-check:
      enable: true  # 是否自动进行latency-test
      url: http://www.google.com
      interval: 3600
  github1: # provider的名称，后期会用到
    type: http
    path: ./profiles/github1.yml # 保存在本地文件的名字，可以随便取
    url: https://raw.githubusercontent.com/freebaipiao/freebaipiao/main/GfwserveClash.yaml
    interval: 36000 # 每36000秒更新一次订阅
    health-check:
      enable: true  # 是否自动进行latency-test
      url: http://www.google.com
      interval: 3600

  github2: # provider的名称，后期会用到
    type: http
    path: ./profiles/github2.yml # 保存在本地文件的名字，可以随便取
    url: https://raw.githubusercontent.com/yu-steven/openit/main/Clash.yaml
    interval: 36000 # 每36000秒更新一次订阅
    health-check:
      enable: true  # 是否自动进行latency-test
      url: http://www.google.com
      interval: 3600

  github3: # provider的名称，后期会用到
    type: http
    path: ./profiles/github3.yml # 保存在本地文件的名字，可以随便取
    url: https://raw.githubusercontent.com/chfchf0306/clash/main/clash
    interval: 36000 # 每36000秒更新一次订阅
    health-check:
      enable: true  # 是否自动进行latency-test
      url: http://www.google.com
      interval: 3600

  github4: # provider的名称，后期会用到
    type: file
    path: ./ermaozi.yaml # 保存在本地文件的名字，可以随便取

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN,github.com,DIRECT
  - DOMAIN,23img.com,PROXY
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
#  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,telegramcidr,PROXY
  - MATCH,DIRECT
    # rules:
    #   - DOMAIN-SUFFIX,google.com,DIRECT
    #   - DOMAIN-KEYWORD,google,DIRECT
    #   - DOMAIN,google.com,DIRECT
    #   - DOMAIN-SUFFIX,ad.com,REJECT
    #   - GEOIP,CN,DIRECT
    #   - MATCH,DIRECT

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
